[package]
name = "uiuifree-actix-web-util"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

authors = ["uiuifree"]
description = "util"
license = "MIT"
repository="https://github.com/uiuifree/uiuifree-actix-web-util"

[dependencies]
dotenv = "0.15.0"
chrono = "0.4"

actix-web = { version = "4" }

mysql = "22.1.0"
mysql_common = {version="0.28.0",features=["chrono"]}
uiuifree-elastic="0.1.21"

# Json
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"